POST /api/2.5/contracts/dda226649ee64264aded84f41f7f7a13/documents?acc_token=3b4905dbfbaf4ffaac2ff8f30dac2ae6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 389
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://localhost/get/50f99bbf153e425cb6b5083b858a0d0f?KeyID=172d32c8&Signature=qhgD%2FYqFEh6Al6YkHzHuZEtWyconzWwU2MlKcvVrNHoeajAuRh4gafOCu9Zc1TVtFsfIc7gSU%2BhU1o2eZvl9CA%3D%3D", 
    "title": "укр.doc", 
    "documentOf": "milestone", 
    "relatedItem": "f4a8d4e93c68484d999dea2648f69fba"
  }
}

Response: 201 Created
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "укр.doc", 
    "url": "http://localhost/get/50f99bbf153e425cb6b5083b858a0d0f?KeyID=172d32c8&Signature=qhgD%2FYqFEh6Al6YkHzHuZEtWyconzWwU2MlKcvVrNHoeajAuRh4gafOCu9Zc1TVtFsfIc7gSU%2BhU1o2eZvl9CA%3D%3D", 
    "format": "application/msword", 
    "documentOf": "milestone", 
    "datePublished": "2018-07-13T16:34:37.727546+03:00", 
    "id": "270392a2094047c3a84023b4271a7e94", 
    "relatedItem": "f4a8d4e93c68484d999dea2648f69fba", 
    "dateModified": "2018-07-13T16:34:37.727563+03:00"
  }
}

